### ISSUE TITLE
Add contingent to tutor and put it into exercises

### ISSUE THREAD

**Issue by leMaik** [Welfenlab/tutor-corrector#1]
The api should return it like this when requesting the overview:

``` json
contingent:
  should: 42
  is: 21
```

**Comment by LittleHelicase** [comment]
I implemented all the backend features
- Welfenlab/tutor-memory-database@ede0ad0259256485d3c528de9c1fb08831f62baa 
- Welfenlab/tutor-rethinkdb-database@7781afa87741dcbedef4eb3109644f578caf6cb4

But I couldn't try it in corrector @leMaik . It tries to log out even though I'm not yet logged in?

**Comment by leMaik** [comment]
Sounds great! The corrector currently does some strange stuff when logging in, I'll look into it.

**Comment by leMaik** [comment]
Login didn't work because the backend checked if there exists a student (user) with the ID, but it has to search for a tutor with the given name. I fixed that in 8c4b479. I'm still debugging to find out why logout is called.

Edit²: Found it! Forgot `->` in a function declaration, so that it was called immediately. CoffeeScript FTW!
Edit³: ~~Now getting "Cannot read property 'contingent' of undefined" when sending a get request to `/api/correction`. The problem is that DB.Corrections.getStatus() now needs a tutor name. I don't really know how this should be fixed. Note: It should not be possible to get the status of other tutors.~~ Fixed.

**Comment by leMaik** [comment]
Works now, but why does the API return fractions for `should`? I currently `ceil` them, but the server should handle this, shouldn't it?

**Comment by LittleHelicase** [comment]
Hey,

jeah I think this is okay. Currently the problem is, that if we round, there will be a situation in which a corrector should do 20, but there are only 19 exercises for her/him. One solution could be to assign each exercise to a tutor after the dueDate. But currently the assignment is done on `/api/exercises/next`. I could fix this in https://github.com/Welfenlab/tutor-slave but that is a low priority thing. If we fix the assignment, I can send exact numbers.

For now you probably should say `21 of ~30` with 21 beeing the `is`value and ~30 beeing the `ceil(should)`value.
