### ISSUE TITLE
Add API request to get a random PDF for correction

### ISSUE THREAD

**Issue by leMaik** [Welfenlab/tutor-corrector#2]
Should include locking, only returning the currently-locked exercise if the tutor already has one locked etc.
`/api/exercises/next` should return a PDF, simply binary, with the correct mime type.

**Comment by LittleHelicase** [comment]
@leMaik I think this is all implemented. The only missing thing is the PDF itself. The API call `/api/exercises/next` locks a new, not already locked, exercise. You can browse through locked, but not finished exercises via `/api/exercises/pending`. A corrector can postpone the correction of one exercise, e.g. if she/he isn't sure and wants some feedback from others. That's why I distinguish between them.

**Comment by leMaik** [comment]
Allright, it would be great if the PDF file request would work. I'll make the correction page work as far as possible today.

**Comment by LittleHelicase** [comment]
Fixed it. We now use the REST API to get the PDF. Currently it will always be the same PDF file, but I will change it when the API is ready

**Comment by leMaik** [comment]
This fix breaks everything for me. :scream:
